### ISSUE TITLE
Bug with some special char in the firstname or lastname

### ISSUE THREAD

**Issue by funkycram** [daggerhart/openid-connect-generic#101]
This will repair the bug :
https://github.com/daggerhart/openid-connect-generic/compare/dev...funkycram:patch-2

**Comment by cyxou** [comment]
Got troubles authenticating users who have say firstName and/or lastName with cyrillic symbols. The patch does its job, I hope it will be integrated asap.

**Comment by daggerhart** [comment]
Merged into dev branch. Thanks!

**Comment by AdvinRoz** [comment]
@daggerhart This bug has been fixed on the dev branch, do you have any idea when this will be merged to master?  (the plugin from the dev-branch is only usable in my case, because of this bug).

**Comment by daggerhart** [comment]
I plan to make a new release within the week. Hopefully by monday or tuesday next week this will be in master and a new version will be out.
