### ISSUE TITLE
Checkbox "Identify with User Name" has some bad effect

### ISSUE THREAD

**Issue by savoierider** [daggerhart/openid-connect-generic#102]
Hi,
If you check the "Identify with User Name" checkbox, if you try to connect with a new username that has an email adresse that already exist in the wordpress user database, you get this error : 
```
object(WP_Error)#8231 (2) {
  ["errors"]=>
  array(1) {
    ["failed-user-creation"]=>
    array(1) {
      [0]=>
      string(21) "Failed user creation."
    }
  }
  ["error_data"]=>
  array(1) {
    ["failed-user-creation"]=>
    object(WP_Error)#8232 (2) {
      ["errors"]=>
      array(1) {
        ["existing_user_email"]=>
        array(1) {
          [0]=>
          string(61) "Désolé, cette adresse de messagerie est déjà utilisée !"
        }
      }
      ["error_data"]=>
      array(0) {
      }
    }
  }
}
```
It's because Wordpress doen't authorize having two user with the same mail adress.

Can you add on option to create the user without any adresse mail in case the adresse mail is already used (or maybe to never keep the adresse mail or create a false random adress mail).

Thank's

**Comment by daggerhart** [comment]
Hi @savoierider,

There is an undocumented hook you can use to modify user information before a new user is created.

Something along the lines of
```
add_filter('openid-connect-generic-alter-user-data', function($user_data, $user_claim) {
  $user_data['user_email'] = 'do some changes here how ever you like';
  return $user_data;
}, 10, 2);
```

The logic for how to modify that user's email is completely up to you. May want to start by querying WP to check if the email address already exists, and then make the change based on your preferences.

**Comment by savoierider** [comment]
Thank's for the trick !
