### ISSUE TITLE
wp rewrite flush (via cli) broken

### ISSUE THREAD

**Issue by flat235** [daggerhart/openid-connect-generic#106]
The merge below was introduced to fix some "headers already sent" problem.
However: Now everytime "wp rewrite flush" is used on the cli, the redirect for the alternate_redirect_uri is broken.
Introduced:
Commit 87470689dbaa770eace59ca4360eeb199dcd69fc
https://github.com/daggerhart/openid-connect-generic/pull/96

Maybe both can be fixed by putting the return after the part responsible for the rewrite rules, but above whatever is responsible for the original problem?

**Comment by drzraf** [comment]
I agree.
`wp rewrite flush` needs `add_rewrite_rule` from `OpenID_Connect_Generic_Client_Wrapper::register` to be run.

I believe inserting the `return` [here](https://github.com/daggerhart/openid-connect-generic/blob/87470689dbaa770eace59ca4360eeb199dcd69fc/openid-connect-generic.php#L103) could make it... as long as it returns before **OpenID_Connect_Generic_Login_Form::register**.

**Comment by flat235** [comment]
Thank you for the PR, as far as I can tell, this works for me (the rewrite rule survives `wp rewrite flush`).
Since I never experienced the reason for PR https://github.com/daggerhart/openid-connect-generic/pull/96 I cannot test if this becomes an issue again or stays fixed.

**Comment by drzraf** [comment]
#96 was because `init()` runs `setcookie()` which in turn triggers "headers already sent" (but maybe not in -production because of the error_reporting level)
