### ISSUE TITLE
Redirect_to broken in 3.4.1

### ISSUE THREAD

**Issue by samueldjack** [daggerhart/openid-connect-generic#108]
We just updated our Wordpress installation to version 3.4.1 of this plugin, and discovered that our login flows get broken. Users log in correctly, but they are then redirected back to the homepage rather than the page they were aiming at. 

For example, if I go to /wp-admin, I first get redirected to our SSO page (as expected) so that I can log in. Once logged in, I am then left at the homepage rather than being redirected back to /wp-admin

We have the "Redirect Back to Origin Page" option checked, so are expecting to see this working correctly.

I've rolled back the plugin to 3.4.0 and it started working again without changing anything else, strongly suggesting the problem is in the new version.

**Comment by drzraf** [comment]
Could you check whether it's related to #98? (trying to apply/revert this sole patch?)

**Comment by samueldjack** [comment]
@drzraf It looks like that patch could well be the problem. With that patch, the redirect cookie is now created only if you use the login button. But we have auto-login set to true, so I don't think the login button ever gets created.

**Comment by daggerhart** [comment]
@samueldjack  and @funkycram could you look at PR #119 and let me know if this resolves the issue?

**Comment by funkycram** [comment]
Yes, thanks a lot, just tested and PR #119 resolves the problem !

**Comment by daggerhart** [comment]
Thanks for the test. I've merged it into dev and will be in the next release.

**Comment by fnicollet** [comment]
Thanks for this patch, it also solved my issue (applyied manually) 👍
