### ISSUE TITLE
invalid user claim

### ISSUE THREAD

**Issue by musti2** [daggerhart/openid-connect-generic#13]
Hi,

I am continuously facing an **'invalid user claim'** error after successfully authentication with our OpenID Connect provider...  I have tested my token and checked the return values and made sure it matches what wordpress is expecting as the username..

My setup is correct as it's working on the original 'Generic OpenID Connect' plugin however the only issue with the original version is that it does not create a user if it does not exist inside wordpress.

**Comment by musti2** [comment]
Error message from the log: object(WP_Error)#4677 (2) { ["errors"]=> array(1) { ["invalid-user-claim"]=> array(1) { [0]=> string(18) "Invalid user claim" } } ["error_data"]=> array(0) { } }

**Comment by robertstaddon** [comment]
What version of PHP are you using?

**Comment by musti2** [comment]
PHP 5.5

**Comment by Blackbaud-JasonRikard** [comment]
Check the `expires_in` value from your token endpoint response. The cookie expires in X seconds dictated by that value. 

https://github.com/daggerhart/openid-connect-generic/blob/f2d2a8083b1f1ceabf4bbb93214b4d10f772cb77/includes/openid-connect-generic-client-wrapper.php#L319

> Expiration time of the Access Token in seconds since the response was generated.

http://openid.net/specs/openid-connect-core-1_0.html#ImplicitAuthResponse

After that time elapses, you will receive the invalid user claim error.

**Comment by radenui** [comment]
I had the same issue and I believe this is a bug: the "sub" field in openid claims is supposed to give the unique identifier of the logged-in user, which you do not necessarily find in user claims with the same name "sub" (for instance, I have this information in the "ID" field of my user claims).

I modified `validate_user_claim()` function in `includes/openid-connect-generic-client.php` to check the right field.

**Comment by rwasef1830** [comment]
@musti2 This maybe due to IdP returning "bearer" in lowercase instead of "Bearer" upper-case in ```token_type``` property in the response. This was fixed in #15
