### ISSUE TITLE
Redirecting to origin page with multiple query parameters

### ISSUE THREAD

**Issue by schamblee** [daggerhart/openid-connect-generic#142]
Hello,

This plugin is a great tool. Thank you for sharing it!

I'm using the setting "Redirect Back to Origin Page" and auto-login so that we can take users from our site directly to a new order we create for them in WordPress so that they can pay for it easily.

Would it be possible to support redirecting back to origin when the origin has multiple query parameters in the URL?

For example, the URL:
`https://woo.example.com/checkout/order-pay/150/?pay_for_order=true&key=wc_order_N9bQlptwQVgga`

becomes this after redirecting:
`https://woo.example.com/checkout/order-pay/150/?pay_for_order=true#038;key=wc_order_N9bQlptwQVgga`

This is because the function `esc_url` encodes ampersands. `&` becomes `#038;`.

Since this URL is used for a redirect and won't be displayed as web content, would it be appropriate to use `esc_url_raw`, which validates the URL in some ways, but does not encode ampersands? ([wordpress codex reference](https://codex.wordpress.org/Function_Reference/esc_url_raw))

Here are the places in code:

openid-connect-generic-client-wrapper.php
`// redirect back to the origin page if enabled
$redirect_url = isset( $_COOKIE[ $this->cookie_redirect_key ] ) ? esc_url( $_COOKIE[ $this->cookie_redirect_key ] ) : false;`

openid-connect-generic-login-form.php
`if ( isset( $_REQUEST['redirect_to'] ) ) {
    $redirect_url = esc_url( $_REQUEST[ 'redirect_to' ] );
}`

If this would not be possible, do you have other suggestions for redirecting back to an origin that has multiple query params?

**Comment by daggerhart** [comment]
Hi @schamblee,

I'm sure we can make this work with some additional logic around decoding urls in the areas you mention.  

Do you want to attempt a PR for this change, or would you prefer someone else attempt it?

**Comment by schamblee** [comment]
Thanks for the response! I can attempt a PR.

**Comment by daggerhart** [comment]
Thanks for the help!
