### ISSUE TITLE
Support IdPs that don't support refresh tokens

### ISSUE THREAD

**Issue by gb056** [daggerhart/openid-connect-generic#144]
Unless I'm reading this wrong, the plugin does not currently support identity providers that don't provide refresh tokens. On logging in to such an IdP on my test site I immediately get a `access-token-expired` error, seemingly from here: https://github.com/daggerhart/openid-connect-generic/blob/dev/includes/openid-connect-generic-client-wrapper.php#L140

Refresh tokens are an optional part of the OAuth2 spec as mentioned in this section: https://tools.ietf.org/html/rfc6749#section-1.5 and so should not be required.

I've not dug deep enough into the code to determine why they're required at this point but there should be a away (in my opinion) of not requiring them so as not to cut out support for any IdPs that don't use them.

**Comment by daggerhart** [comment]
That makes sense to me, thanks for bringing this up. 

Would you like to attempt a PR for this change or would you prefer someone do it?

**Comment by benochen** [comment]
I'm interessted to dig into the plugin. I can submit a PR in the nex weeks if you want.

**Comment by KrzychuR** [comment]
Hi all,

Firstly, thanks a lot for the effort! I'd like to use this plugin with Azure B2C Active Directory (see https://azure.microsoft.com/en-us/services/active-directory-b2c/ )

I think B2C supports refresh tokens but.. I had to comment out from https://github.com/daggerhart/openid-connect-generic/blob/dev/includes/openid-connect-generic-client-wrapper.php#L124 to the end of procedure to be able to finish authentication process.

Let me know if you need more info or test site to play with AAD.

BTW do you expect any other issues with Azure B2C? :)

**Comment by KrzychuR** [comment]
One more, according to: https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-reference-tokens B2C supports refresh tokens

**Comment by KrzychuR** [comment]
OK... sorry for a lot of posts but.. I finally configured plugin to work with B2C, to receive refresh token we have to add 'offline_access' to scopes and.. tada! :)

The next question is... email mapping... but.. I'll create separate issue for it.

**Comment by CrowdHailer** [comment]
Hi, we have run into the same issue using [did.app](https://did.app) as our identity provider, which does not currently issue refresh tokens

Can I ask if there is any progress on this PR

**Comment by timnolte** [comment]
@daggerhart I'm working on a PR for this. Just doing some testing now.
