### ISSUE TITLE
validate_token_response token_type check should be case-insensitive (fails with keycloak)

### ISSUE THREAD

**Issue by rwasef1830** [daggerhart/openid-connect-generic#15]
Hello,
Thanks for a very useful WordPress plugin. Was just testing it with KeyCloak 2.3.0 final and noticed a very minor bug. In the ```validate_token_response``` there is a check that compares the ```token_type``` value to ```Bearer``` using ```!==```. 

This does a case-sensitive check that fails with implementations that return ```bearer``` such as keycloak and causes login to fail with "Invalid token response".

Relevant keycloak bug: https://issues.jboss.org/browse/KEYCLOAK-1855

According to the OpenID Connect specification, this check should be case-insensitive.
https://tools.ietf.org/html/rfc6749#section-4.2.2

Thank you.

**Comment by robertstaddon** [comment]
Thank you for your fix! https://github.com/daggerhart/openid-connect-generic/pull/16

**Comment by rwasef1830** [comment]
Hey, @robertstaddon I think this should be merged into the dev branch as well.

**Comment by robertstaddon** [comment]
Done!
