### ISSUE TITLE
One configuration for all blogs on Multi-Site Install

### ISSUE THREAD

**Issue by connerbw** [daggerhart/openid-connect-generic#153]
This is a follow up to: https://github.com/daggerhart/openid-connect-generic/issues/79

Expected: One configuration for the entire network.
Actual: A separate configuration for each blog. 

I was looking at the code. To get what I want I have to change.

 + `is_admin()` to `is_multisite() && is_network_admin()`
 + `add_action( 'admin_menu', array( $settings_page, 'admin_menu' ) );` to `add_action( 'network_admin_menu', array( $settings_page, 'admin_menu' ) );`
+ `add_options_page( ...` to `add_submenu_page( 'settings.php' ...`
+ `<form method="post" action="options.php">` to `...`

I'm happy to submit a PR that fixes for my use case (activated with some wp-config.php `define` or something else) but I would appreciated some clarfication on @daggerhart last comment in #79 

> I develope against a multisite install, so I'm pretty comforable closing this issue with an answer of "Yes, works with multisite".

Am I missing something? Is _"One configuration for the entire network"_ already possible?

**Comment by connerbw** [comment]
#wontfix

**Comment by daggerhart** [comment]
Hey @connerbw,

Sorry for the months of no-reply, I had my email filters setup wrong for most of last year and I missed a lot of issues. 

I'm open to a PR that allows people to use one configuration for an entire network. I don't think we want to replace the current per-site configuration, as someone may be using that already to control sites differently. But if you still want to take a stab at a PR that provides a new feature that is network-wide configuration, that'd be great.

**Comment by connerbw** [comment]
It's OK. 

I'm not working on this anymore. Pressbooks has another solution now. 

Thanks for your hard work.
