### ISSUE TITLE
Added  a new filter to change user_claim

### ISSUE THREAD

**Issue by chdenat** [daggerhart/openid-connect-generic#168]
Hello,

1st, great job ! It works like a charm !

In our company, we have 3 ways to be authenticated into our OIDC server in order to be then logged in all our apps (TOTP, SAML and laptop secured key dongle) and,  on our WP site we need email to be authenticated, not sub.

Both 2 first authent mechanisms  returns all the information required , but using the dongle, for security reasons, we have only the sub, no name, no email ...

So I added a new filter in first lines of  **create_new_user** method to change the user_claim before checking it.
This filter, in our implementation, is calling our user DB to retrieve the email.

`  $user_claim = apply_filters( 'openid-connect-generic-fix-user-claim', $user_claim );
  $values_missing = false;`

I named it 'fix-user-claim'  because the "alter-user-claim' has another purpose and it is called too late.

Home it will help.

Christian

**Comment by daggerhart** [comment]
Thanks for this issue. I'm looking at the code, and don't see any reason why we wouldn't just move the existing filter (`openid-connect-generic-alter-user-claim`) to the top of the create_new_user() method. Seems like if someone wants to alter the user claim, they would want to do that before the rest of the method.

What do you think?

**Comment by chdenat** [comment]
Thanks for replying.

Yes it is exactly  this. We need to alter the claims on one use case.

As I wrote before, using a dongle secured keys, it is not possible to get the email. But on some legacy systems we need it to login
. 
So by  adding a new filter here , it is possible to get the required information (by requesting our LDAP). the "alter-user-claim" filter is called too late in the process.

In our company, we have 5000+ colleagues that can potentially logged in, using a dongle... so, after implementing this fix, they can login into this system. It is quicker than fixing the 5000 dongle keys ... :)

**Comment by daggerhart** [comment]
I've moved the `openid-connect-generic-alter-user-claim` filter to the top of the method. You should be able to use that for your purposes now. Let me know if there is more to do here. And thanks again for the request!
