### ISSUE TITLE
Use custom login link rather than /wp-admin

### ISSUE THREAD

**Issue by subrato30** [daggerhart/openid-connect-generic#169]
We have anchor tags for login and would like to use that link rather than https://www.site.com/wp-admin link. (We also intend to use SSO mechanism which is provided by our Identity solution provider). How do I make the link show login using those anchor tag (e.g. Login to comment link should pop-up the box provided by the solution provider) rather than redirecting to wp-admin page.

**Comment by daggerhart** [comment]
This should be handled by enabling the SSO option. When the login approach is set to SSO, users will bypass the wp-admin page during login attempts.

Closing for now. Feel free to reopen if SSO isn't working as expected.

**Comment by subrato30** [comment]
hi @daggerhart 

how would I handler editors who still need to login through the wp-admin link? We have 2FA enabled (a default requirement on WordPress VIP). When I enabled that option I had no way for admins & editors to login using wp-admin
