### ISSUE TITLE
Checked "Identify with User Name" but new user created 

### ISSUE THREAD

**Issue by Arnold85** [daggerhart/openid-connect-generic#175]
Hi everyone,
I'm no programmer and I think I just dont understand enough of how openId works.
What I want: 
sell an e-learning course with woocommerce. When a new user is created I send an HTTP-request to Azure so that a user is created there aswell. In the end the user created in Wordpress is updated so that it has the same username as the user in Azure Active Directory.
With the "Identify with User Name" checkbox checked, I thought that openid-connect would compare the username from the openID provider (Azure) with the usernames in Wordpress and connect these together if they match.
But instead when I login with the Azure/Microsoft account a new user is created in Wordpress.
So how does the plugin compare the login data to the wordpress database to determine if that user already exists?

**Comment by daggerhart** [comment]
Is your WP a single site or multisite?

**Comment by daggerhart** [comment]
Closing as stale. Please reopen if you have more specifics.
