### ISSUE TITLE
Log out loop with keycloak

### ISSUE THREAD

**Issue by ChaseHall** [daggerhart/openid-connect-generic#182]
I have require logged in to view site turned on, when I go to logout, it just "refreshes" the page, as it logs me right back in with OAuth from keycloak.

What can I do to actually sign out? (Ideally have it sign me out of keycloak)

**Comment by daggerhart** [comment]
There is a setting named "End Session Endpoint URL" that should be usable. If you set that value to keycloak's logout url, then the user should get redirected there automatically when they perform a WP logout. (see: https://github.com/daggerhart/openid-connect-generic/blob/f401b3f53bf8f8a043fb51be4e6ed1be749fbb4a/includes/openid-connect-generic-client-wrapper.php#L51)

I don't know keycloak well enough to know what that URL should be. Let me know if this works out, or if you run into any problems.

**Comment by ChaseHall** [comment]
I have the URL set, I should've included that sorry!

     https://sso.chasehall.design/auth/realms/realm/protocol/openid-connect/logout

This URL when directly visited *does* sign me out of keycloak, but I visit the WP site again and it keeps me signed in there.

**Comment by ChaseHall** [comment]
Closing since it appears to work on my second wordpress site, I'm sure I just have this one setup in a stupid way.

Thanks for helping.
