### ISSUE TITLE
Wordpress links to wrong user

### ISSUE THREAD

**Issue by yuzunay** [daggerhart/openid-connect-generic#197]
Hi, 
My openid authentication works without problem and can sign-in to my WP. However; it signs me with different user.  Signed in user is not included in any value of access and id tokens. In the settings I entered "sub" for user identification. So I expect to login with testuser. But cannot.  I changed username and add a new user to my WP. But no result. I appreciate you could help. 

array(2) {
      [0]=>
      array(7) {
        ["sub"]=>
        string(11) "testuser"
        ["success"]=>
        bool(true)
        ["message"]=>
        string(21) "You accessed my APIs!"
        ["firstname"]=>
        string(5) "myname"
        ["lastname"]=>
        string(6) "mysurname"
        ["email"]=>
        string(17) "myname@gmail.com"
        ["group"]=>
        string(13) "Administrator"
      }
      [1]=>
      array(6) {
        ["iss"]=>
        string(19) "test.example.com"
        ["sub"]=>
        string(12) "testuser"
        ["aud"]=>
        string(13) "testclient"
        ["iat"]=>
        int(1595058517)
        ["exp"]=>
        int(1595062117)
        ["auth_time"]=>
        int(1595058517)
      }
    }
  }

**Comment by timnolte** [comment]
@yuzunay the WordPress account that you created for `testuser` did it also have it's email address set to `myname@gmail.com`? By default the identity it matched based on email address unless you check the box "Identify with User Name".

**Comment by yuzunay** [comment]
> @yuzunay the WordPress account that you created for `testuser` did it also have it's email address set to `myname@gmail.com`? By default the identity it matched based on email address unless you check the box "Identify with User Name".

Yes @timnolte  email address is correct. I also checked 'Identify with User Name'. I tested both (unchecking Identify with User Name) but still connects with another user.

**Comment by timnolte** [comment]
@yuzunay are you able to look at all of your user data. Every user has a meta key `openid-connect-generic-subject-identity` added with the value of the matching identity. This is added when a user logs in for the first time through SSO. Once a user is authenticated this is the key that is used to match to the WordPress user. I suspect that the user that is getting authenticated improperly has the wrong value set here. If you can remove this meta key it should fix the issue.

**Comment by yuzunay** [comment]
Thank you very much @timnolte when I delete meta key it is resolved.
