### ISSUE TITLE
Use a popular OAuth2 client library

### ISSUE THREAD

**Issue by daggerhart** [daggerhart/openid-connect-generic#23]
Ideally there is a reliable php OAuth2 client library out there that we can incorporate instead of rolling our own.  First glance finds: https://github.com/thephpleague/oauth2-client (minimum PHP 5.5)

Second glance finds: https://github.com/Lusitanian/PHPoAuthLib - php 5.3, late update July 12th 

Using a client library would allow us to focus on the WordPress side of plugin and greatly simplify the custom code.

Thoughts / suggestions?

**Comment by rwasef1830** [comment]
It could simplify things, but it would hinder implementing superset features outside OAuth 2.0 like the discovery endpoint, integrated logout ... etc.

thephpleague seems better implemented and more well-known than the second one.
