### ISSUE TITLE
Host header in user info request ignores port

### ISSUE THREAD

**Issue by xou816** [daggerhart/openid-connect-generic#30]
The "Host" header that is set by request_userinfo ignores the parsed port. 
With Keycloak, it resulted in invalid issuer errors.
Modifying line 207 to `$host = $parsed_url['host'].':'.$parsed_url['port'];` seems to fix it.

**Comment by daggerhart** [comment]
Hi @xou816 

I've added this to the dev branch. If you have time could you please test that it works as expected?

Thanks,
Jonathan

**Comment by xou816** [comment]
Hi!
Thank you for handling this issue!
It seems to work as expected for my setup (Keycloak 2.5.0.Final + WordPress 4.7.3) :)

**Comment by ThomasWilhelmUR** [comment]
Hey guys, sorry to open this up again but I think you may be able to help me.
I am also trying to connect it to a Keycloak IDP but get this error: "cURL error 7: Failed to connect to localhost port 8089: Connection refused"

Since it works for you, Alexandre, can you show me your keycloak and plugin setup?

Thanks, Thomas

**Comment by daggerhart** [comment]
Hi Thomas,

One thing to make sure of is that you're using HTTPS for the WordPress site. If you don't have HTTPS setup, then you'll need to check the plugin setting:  'Disable SSL Verify'.

Another thought, I assume keycloak is installed on your local machine and knows about 'localhost'. Is that correct?

Jonathan

**Comment by ThomasWilhelmUR** [comment]
Thanks for your reply, meanwhile i provided some more info here: 
https://github.com/daggerhart/openid-connect-generic/issues/53 

SSL verification is disabled since I'm on localhost (in docker).

Redirects work fine and I also checked the JWTs which look fine (for the auth request).
