### ISSUE TITLE
LemonLDAP SSO + OpenID Connect

### ISSUE THREAD

**Issue by olkitu** [daggerhart/openid-connect-generic#33]
I installed OpenID Connect and login working but when returning back to WordPress i get on plugin debug log:

> object(WP_Error)#10206 (2) {
  ["errors"]=>
  array(2) {
    ["http_request_failed"]=>
    array(1) {
      [0]=>
      string(21) "URL was incorrect."
    }
    ["request_authentication_token"]=>
    array(1) {
      [0]=>
      string(40) "Request for authentication token failed."
    }
  }
  ["error_data"]=>
  array(0) {
  }
}

**Comment by daggerhart** [comment]
Looks like the URL for the IDP's token failed. This is the "Token Validation Endpoint URL" in the plugin settings. Can you verify that the endpoints you've provided to the plugin settings are correct?

It could also be related to the "Verify SSL" settings. Could you try that both as enabled and disabled to see if you get different results?

**Comment by olkitu** [comment]
Thanks, i have typo on Token Validation Endpoint. Now i get another error about token

> object(WP_Error)#10203 (2) {
  ["errors"]=>
  array(1) {
    ["invalid-token-response"]=>
    array(1) {
      [0]=>
      string(22) "Invalid token response"
    }
  }
  ["error_data"]=>
  array(1) {
    ["invalid-token-response"]=>
    array(4) {
      ["token_type"]=>
      string(6) "Bearer"
      ["access_token"]=>
      string(64) "439ad54accf14bf7c7a0ac88251c38eadf8490XXXXXXXXXXXXXXXX"
      ["id_token"]=>
      NULL
      ["expires_in"]=>
      NULL
    }
  }
}

**Comment by daggerhart** [comment]
This is happening because the "id_token" is NULL.  That value is a requirement of the OpenId specifications, so I suspect the IDP to provide it.

Maybe there is an issue with the previous failed attempts. Could you trying logging out of both WordPress and your IDP and then trying to login again?

**Comment by olkitu** [comment]
Thanks very much, i found setting on LemonLDAP: ID Token signature algorithm, i changed value RSS512 to  HS256. Now login works, thank you.
