### ISSUE TITLE
Logout fails

### ISSUE THREAD

**Issue by geopal** [daggerhart/openid-connect-generic#39]
You log in with openid connect and wordpress creates a user if there is not one and then logs in. After selecting to log out, wordpress logs out the user but when you try to login again with openid connect then you login automatically like you didn't log out. This problem can be solved only by cleaning browser's cache (Ctrl + Shift + Del).

**Comment by daggerhart** [comment]
HI @geopal, 

It seems this is related to the #38 issue, in that the user is not being logged out of the IDP. I'm going to close this issue and we can continue working through the problem on 38.  Apologies if this is a separate issue, please re-open if I've misunderstood.
