### ISSUE TITLE
Don't force re-login after token expiration

### ISSUE THREAD

**Issue by svenvanhal** [daggerhart/openid-connect-generic#41]
When a user is logged in and the access token expires, the user is redirected to the login page and a notification ("Session expired. Please login again.") is displayed.

It's not always necessary / desirable to be redirected to the login page. When a user was logged in, leaves the site and returns at a later moment, the user is currently -always- redirected to the login page if the access token has expired.

I would like to propose to make [this error redirect](https://github.com/daggerhart/openid-connect-generic/blob/cdf2629aa31e86c2e7bcd55f3551623769e69abd/includes/openid-connect-generic-client-wrapper.php#L162) optional.

**Comment by daggerhart** [comment]
Good suggestion.  I've created a PR with this change and will merge it in on the next release.
