### ISSUE TITLE
Register Sequence

### ISSUE THREAD

**Issue by cedrox** [daggerhart/openid-connect-generic#43]
Hello, 
I try to add register via sso to my site but it seem that it's not working properly.
Let me explain :
1. I click register on my site
2. I am redirected to sso provider page
3. User create his account and receive a mail (parameter sign and data-info are send to the auth server to change the redirect uri)
4. User click in the mail and he is redirected to our site.
5. Website(plugin actually) should create a token and send to specific page (/welcome) 
> here we have a problem. we are redirected to an output 0 (url : https://[mysite]/wp-admin/admin-ajax.php?action=openid-connect-authorize&state=[mystate]&code=[mycode])
![image](https://user-images.githubusercontent.com/10764310/30690932-3272e270-9ec6-11e7-9690-bb2c6de76c45.png)

Plugin seem to not process parameters to generate an access token. It should get a state and code in a local storage to redirect user and create new suscriber... This is quite different from a common login sequence...

Can you please assist on this ?
Thanks

**Comment by mdomsch** [comment]
I have a similar need.  For registration, I expect the sequence to be:
1.  /wp-register.php redirects to
2.  /wp-login?action=register   redirects to
3.  my application's custom registration URL, of the form:

https://idp.example.com/auth/realms/myrealm/protocol/openid-connect/registrations?client_id=myclient&redirect_uri=https%3A%2F%2Fmyapp.example.com%2F&state=ee4fd4a4-1031-4757-bd78-aeb8a9071cb9&nonce=e24858d3-d194-455d-8c8c-95d51083265e&response_mode=fragment&response_type=code&scope=openid

which shows MY registration page, and returns back to the wordpress app.

**Comment by cedrox** [comment]
Hello;
To get this done, we need that the plugin process the parameters in the url to extract access_token and / or id_token.Then, plugin must have in its local storage things to check that the answer comes from the server proper auth server (for security). This done, it must recover a state in its local storage, and deduce a page to redirect the user. 
I think this is an interesting feature as user is not redirected to the identity provider validation page after mail validation…
Thanks

**Comment by cedrox** [comment]
Merge into Thread https://github.com/daggerhart/openid-connect-generic/issues/44
