### ISSUE TITLE
Override WP user registration form

### ISSUE THREAD

**Issue by mdomsch** [daggerhart/openid-connect-generic#44]
When using SSO, user registration needs to happen on my IDPs pages, not within WP.  For user registration, I expect the sequence to be:

/wp-register.php redirects to
/wp-login?action=register redirects to
my application's custom registration URL, of the form:
https://idp.example.com/auth/realms/myrealm/protocol/openid-connect/registrations?client_id=myclient&redirect_uri=https%3A%2F%2Fmyapp.example.com%2F&state=ee4fd4a4-1031-4757-bd78-aeb8a9071cb9&nonce=e24858d3-d194-455d-8c8c-95d51083265e&response_mode=fragment&response_type=code&scope=openid

which shows MY registration page, and returns back to the wordpress app.

I have not found a hook with which a plugin can provide its own registration URL rather than hit the wp-signup form.

**Comment by cedrox** [comment]
Thanks @mdomsch for clarifying our needs. @daggerhart, do you think this kind of scenario could be implemented ? I am developper (not wp one unfortunatly) but maybe if you can give some inputs about how to implement this cleanly, I could try something...

**Comment by mdomsch** [comment]
https://wordpress.stackexchange.com/questions/46848/how-to-modify-the-register-link-in-the-login-page
under "not multisight, eh?"

**Comment by daggerhart** [comment]
@cedrox I think we can implement a redirect like @mdomsch linked to relatively easily.  I'll work something up soon.

**Comment by cedrox** [comment]
Hello and thanks for your reply.
I already try to update plugin but I am not sure that this is the standard method... This work for us as my idp can adapt a bit the redirect process...
We add parameter auth-info where we add a small json like this : {"RootUrl":"rurl"}
![image](https://user-images.githubusercontent.com/10764310/31540873-2423ed9c-b00d-11e7-8434-e0f9e8f8b567.png)

but I am not sure this is the standard way to do it...

Thanks

**Comment by cedrox** [comment]
Anyway, maybe it can be nice to have this auth-info parameter expose in the back office ?

**Comment by daggerhart** [comment]
Circling back around to all the issues here where I've failed to resond.

Do you still need work done on this issue?

**Comment by mdomsch** [comment]
I've moved on to other projects. Don't keep this open on my account.
