### ISSUE TITLE
Nonce parameter

### ISSUE THREAD

**Issue by cedrox** [daggerhart/openid-connect-generic#45]
Hello, 
Nonce parameter is not generate by the plugin. Is there any option to activate it ?
http://openid.net/specs/openid-connect-core-1_0.html#NonceNotes

Thanks

**Comment by pjeby** [comment]
The nonce parameter is optional for the Authorization Code flow, which is what this plugin uses.  See:

http://openid.net/specs/openid-connect-core-1_0.html#AuthRequest

In this flow, the role of the nonce is effectively handled by the `state` parameter.  States are randomly generated, valid for no more than 3 minutes, and invalidated upon first use -- thereby preventing replay attempts.

**Comment by daggerhart** [comment]
Closing this for now. @cedrox if you want to re-open with additional thoughts/needs around nonce-ing, please do so. Thanks!
