### ISSUE TITLE
Usage with League OAuth2 server?

### ISSUE THREAD

**Issue by wgmv** [daggerhart/openid-connect-generic#48]
I'm trying to use your plugin with laravel passport - which is built on top of the League OAuth2 server.
After logging in to my app (the redirect works) I don't see the expected "authorize" window but another login window which looks like a simple .htaccess login window.

I'm just checking out your plugin / looking for a generic oauth2 client

I was wondering if this should work or not and if you have a hint where I should look or let me know if the question is too specific.

Thanks,
Walter

**Comment by wgmv** [comment]
sorry this was my fault - I put the wrong client_id into the config.
However now I get "Invalid token response". I'm taking a look at the source code:

`if ( ! isset( $token_response['id_token'] ) || ! isset( $token_response['access_token'] ) ||
		     ! isset( $token_response['token_type'] ) || strcasecmp( $token_response['token_type'], 'Bearer' )
		) {
			return new WP_Error( 'invalid-token-response', 'Invalid token response', $token_response );
		}`

**Comment by daggerhart** [comment]
Hi @wgmv,

Sorry for the delay, I broke my local dev setup earlier in the week and then had a series of long meetings. 

I'm not exactly sure what the issue is here. I'll dig into this over the weekend and see what I can find.

**Comment by wgmv** [comment]
Hi thanks for your reply! I actually switched to another oauth client plugin now. So please don't spend too much time on this problem ;) I liked your plugin though!

**Comment by daggerhart** [comment]
@wgmv No worries, I'll still dig into this issue. At some point I'd like to start using the league's oauth client within this plugin, so the more experience I get with it the better.

Out of curiosity, which plugin did you end up using? I made this plugin because I couldn't find another I liked, so it'd be great to know what else is out there.

Thanks!

**Comment by wgmv** [comment]
I ended up using miniOrange oauth https://www.miniorange.com/wordpress-oauth-login-solution

**Comment by terenc3** [comment]
I like to contribute my two cents here. I had the some problem with keycloak but adding openid to the scope solved it.

Found via http://lists.jboss.org/pipermail/keycloak-user/2018-February/013181.html

**Comment by ryancwalsh** [comment]
Like the first post above, I'm trying to use this plugin with [Laravel Passport](https://laravel.com/docs/5.8/passport), too!

And I'm still stuck. 

But https://github.com/benbjurstrom/passport-custom-jwt-claims and https://auth0.com/docs/tokens/id-token#id-token-payload look like they are hinting at the answer to the earlier question "[What is `$token_response['id_token']` as this seems to be missing?](https://github.com/daggerhart/openid-connect-generic/issues/48#issuecomment-346700642)" 

I'll continue to try to figure out. I'll ultimately probably post at https://stackoverflow.com/q/35643938/470749 too.
