### ISSUE TITLE
Sending the wrong id_token_hint at logout

### ISSUE THREAD

**Issue by pjeby** [daggerhart/openid-connect-generic#54]
As with #49, this is a problem where the plugin assumes only one session is active at a time.  It sends the `id_token` from the *most recent login*, rather than the login relevant to the current session.  Depending on the IdP, this may or may not log out the correct session.

In the case of Keycloak, this results in a "We're sorry...  An internal server error has occurred" when you:

* log in via browser A
* log in via browser B
* log out in browser A

The session in browser A is logged out, and browser B's session is unaffected, but the error message and failure to redirect properly should be fixed.

With some modification to PR #52, the relevant id token could be saved as part of the session for use at logout.  Unfortunately, `wp_logout()` destroys the current session before invoking the `wp_logout` action, making it impossible to access the token.

For the plugin's own use of wp_logout, this is easily worked around.  And for the standard WP logout process via `wp-login.php`, a hook could be added to the `login_form_logout` action.

Probably the way to do this would be to store the id_token in a variable from `ensure_tokens_still_fresh()`, and in another method tied to the `login_form_logout` action.  Then instead of querying the user metadata, it would use the contents of the variable.  This should cover all uses of `wp_logout` that don't happen during `init`.

(All that being said, it's going to be kind of a PITA to implement.  The alternative would be to just not send the token hint at all, unless there aren't any other WP sessions active for that user.  The OIDC spec doesn't *require* the hint, after all...)

**Comment by daggerhart** [comment]
Fixed in another PR
