### ISSUE TITLE
Identity Key problem.

### ISSUE THREAD

**Issue by DioDread** [daggerhart/openid-connect-generic#7]
Greetings, I have little trouble with Identity Key. After user_info is queried and authorization is performed. On main page wordrpress shows 'sub' as currently logged in user's name, no matter which Identity Key I set up in plugins configurations. Thanks in advance!

**Comment by robertstaddon** [comment]
@DioDread, I think that you may be misunderstanding "Identity Key". This is not the username of the user to log in. This is the location in the user claim array to find the user's identification data. If you're able to successfully log in with any user into your OpenID Connect server, it's probably working fine for you.

OpenID Connect allows you to log into the site with any user that authenticates correctly on the OpenID server. If you are already logged into your OpenID server as a user named "sub", than OpenID Connect is going to automatically log you into the site with a user account named "sub". To log in with a different account, first go to the OpenID Connect site and log out of your "sub" user account. Then use OpenID Connect to log in as a different user. If your login is successful, a corresponding user account will be automatically created in WordPress and you'll be logged in as that user.

**Comment by DioDread** [comment]
Sorry for misguidance. I mean it showing sub's value from claims - that is subject (I supposed to think some sort of unique ID or SAML related code), kinda 01210ade0a20d etc. But after i changed it to preferred_username and delete user from wordpress db it now show username and not sub value. Maybe it was caused by some configurations.

**Comment by robertstaddon** [comment]
Ok. I'm connecting into an OpenID Connect server hosted on Drupal (https://www.drupal.org/project/oauth2_server) and "preferred_username" is what worked for me. So is everything working well for you with that set?

Perhaps I should change the description under the field to this:

> Where in the user claim array to find the user's identification data. Possible standard values: preferred_username, name, or sub. Defaults to preferred_username. If you're having trouble, try using "sub".

**Comment by DioDread** [comment]
Yep, thank you, all fine now.
