### ISSUE TITLE
Login URL has a ? in it...

### ISSUE THREAD

**Issue by hesscj** [daggerhart/openid-connect-generic#76]
Our Login Endpoint URL has a ? in it so that it breaks the plugin:
https://example.com/authorize.php?request=authorize

When the authentication link is then built it becomes:
https://example/authorize.php?request=authorize?response_type=code&scope=....

Becuase there are two question marks it doesn't work.

I don't consider myself a strong programmer but my suggestion is to change the make_authentication_url() function to check for a ? and then set a variable to use as either a ? or & based on the result:

	function make_authentication_url() {
		if(strpos($this->endpoint_login,'?') !== false){$separator = "&";}else{$separator = "?";}
		$url = sprintf( '%1$s%2$sresponse_type=code&scope=%3$s&client_id=%4$s&state=%5$s&redirect_uri=%6$s',
			$this->endpoint_login,
			$separator,
			urlencode( $this->scope ),
			urlencode( $this->client_id ),
			$this->new_state(),
			urlencode( $this->redirect_uri )
		);
			
		return apply_filters( 'openid-connect-generic-auth-url', $url );
	}

I've tested this with no ? in the URL and with one and it created the correct authentication url both times. I'd put this in as a pull request but honestly, I'm not sure how to do that... :)

**Comment by daggerhart** [comment]
Hi @hesscj 

Do you still need this feature?

**Comment by hesscj** [comment]
I'm currently using a modified version of the plugin to make this work for
now. I'd love to be able to use the standard one and if this was available
I should be able to.

Thanks,
Chris

**Comment by daggerhart** [comment]
Committed some code very similar to this into the dev branch. Thanks!
