### ISSUE TITLE
Any way of forcing the standard WP login screen when Auto Login is enabled?

### ISSUE THREAD

**Issue by samueldjack** [daggerhart/openid-connect-generic#77]
I'm planning to enable the Auto Login option so that all Logins to our WP site go through OpenId Connect.

But just suppose that something goes wrong with the OpenId Connection server. Is there then a way of forcing the standard WP login screen to be shown so that I can log in the normal way? 

I'm assuming that if I couldn't login via Open Id connect I wouldn't then be able to get to the admin dashboard to change the Login Type setting.

**Comment by daveboulden** [comment]
As a last resort, if you can access the database, then find the entry in wp_options for the plugin and change:

s:10:\"login_type\";s:4:\"auto\";

to

s:10:\"login_type\";s:6:\"button\";

to switch back to standard WP login with an OpenID login button.

**Comment by samueldjack** [comment]
That's the same conclusion I came to!

Many thanks!
