### ISSUE TITLE
Is this plugin compatible with a multi-site setup?

### ISSUE THREAD

**Issue by daveboulden** [daggerhart/openid-connect-generic#79]
We have employed this plugin on two sites, one being a single site, the other a multisite setup with two sites in the network. The single site works correctly.

The multisite allows us to log in just fine, but logging out is not working. Checking the network traffic in the browser developer tools, it seems the multi-site logout process doesn't redirect to the authorisation server, so the user is only logged out of WordPress and when requesting the login form, the user is still logged in.

Should the plugin work on a multi-site instance of WordPress?

**Comment by daveboulden** [comment]
This can be closed. It turns out another plugin had hooked a function to the action "wp_logout" and was failing, halting the WPO logout process after logging out before performing redirection and so preventing the redirection on logout to the end-session endpoint of the auth server.

**Comment by daveboulden** [comment]
I am re-opening this issue as there is still something related to this that is particular to multi-site installs. I am using the hooks:

```
openid-connect-generic-update-user-using-current-claim
openid-connect-generic-user-create
```

to initiate, upon login, the storing of claims data against a plugin (WishList Member) that is specific to the user on that site rather than just the user globally in the network sense. I adapted the suggested code from the 2nd last comment here: https://github.com/daggerhart/openid-connect-generic/pull/29

However, when using this on a multisite install, those hooks only fire when the user first logs into the network, but not when logging in to a second sub-domain on the same network. Is there another hook that can be employed to catch the first time the user logs in to another site on the same network or, alternatively, where in the code could I implement one?

**Comment by daveboulden** [comment]
I am re-opening this issue as there is still something related to this that is particular to multi-site installs. I am using the hooks:

```
openid-connect-generic-update-user-using-current-claim
openid-connect-generic-user-create
```

to initiate, upon login, the storing of claims data against a plugin (WishList Member) that is specific to the user on that site rather than just the user globally in the network sense. I adapted the suggested code from the 2nd last comment here: https://github.com/daggerhart/openid-connect-generic/pull/29

However, when using this on a multisite install, those hooks only fire when the user first logs into the network, but not when logging in to a second sub-domain on the same network. Is there another hook that can be employed to catch the first time the user logs in to another site on the same network or, alternatively, where in the code could I implement one?

**Comment by daggerhart** [comment]
Hi Dave,

Disclaimer: Multisite is not an area of expertise 😅, so this reply is going to be a scatter of information. Hopefully some of it helps.

Looking at `wp-includes/ms-functions.php`, I think I see some hooks that may be useful.

* Action: `add_user_to_blog`
    https://core.trac.wordpress.org/browser/trunk/src/wp-includes/ms-functions.php#L200
    It seems like this is useful, but this would only be for when the user is initially added to a site. I don't think it would help on the 2nd visit to the sub-site.
* Action: `remove_user_from_blog`
    https://core.trac.wordpress.org/browser/trunk/src/wp-includes/ms-functions.php#L238
    Similar, but when the user is removed from a site, not when they are leaving a specific sub-site, nor logging out.

Digging in more to the WP database, I'm realizing WP doesn't track usermeta per blog (site). Instead it seems to juggle a prefix for the user meta data. Not sure if this is relevant, but it was good to find out.
Example:
```
// remove all perms
$table_prefix = $wpdb->get_blog_prefix();
delete_metadata( 'user', 0, $table_prefix . 'user_level',   null, true ); // delete all
delete_metadata( 'user', 0, $table_prefix . 'capabilities', null, true ); // delete all
```
 
I'm not sure if this information is too helpful, I'm still just getting more familiar with multisite.

I think I need some more information about your multisite setup before I can determine a good solution. Could you further describe the sites, the user flow from one site to another, when you want to gather the user claim, and how you want to use that claim information in a per-blog fashion?

**Comment by daggerhart** [comment]
Thanks, I think that helps. 

Maybe this is a dumb question, but could you check the user's WLM access each time they login (including the first time) and update their accounts using the WLM api as appropriate?

Something like:
```php
add_action('openid-connect-generic-user-create', 'my_update_wlm_access', 10 , 2);
add_action('openid-connect-generic-update-user-using-current-claim', 'my_update_wlm_access', 10, 2);

function my_update_wlm_access($user, $user_claim) {
  $can_access_site_1 = !empty($user_claim['something_or_other']);
  
  if ($can_access_site_1) {
    wlm_api_grant_access($user, 1);
  }
  else {
    wlm_api_remove_access($user, 1);
  }

  $can_access_site_3 = !empty($user_claim['another_thing']);
  
  if ($can_access_site_3) {
    wlm_api_grant_access($user, 3);
  }
  else {
    wlm_api_remove_access($user, 3);
  }
}
```

Obviously there is a lot of made-up code there, I have no idea how WLM works, but the general idea is to check the user's WLM related access to all the sites each time they login.

Aside from something like that, I can't find a way to check a user's claim when on site 3 because if the user is already logged into site 1 there doesn't appear to be anything that really happens within WP when the user accesses site 3.

The `add_user_to_blog` action fires when the user is first added to a blog for the first time, but it wouldn't ever fire for that user a second time.

**Comment by daveboulden** [comment]
Thanks Jonathan. Unfortunately, I don't believe the WLM API allows cross-site access through its API. At least I now know I will have to find a workaround to set both blog's WLM profile upon first log-in, probably direct to the database. 

I will post details of whatever solution I end up with.

Many thanks for taking a look at this!

**Comment by uira** [comment]
@daveboulden please just say that you have a PR for us... ;)

**Comment by uira** [comment]
But did you have success to use the plugin in a MultiSite installation, right?

Can you share the diff nedeed for set this working?

**Comment by daveboulden** [comment]
There are no changes needed, the plugin works on a multisite install for the task it is intended to perform. The issue was that certain hooks were only fired on the first login attempt to the network, irrespective of which blog was hit first. Other than that, which is not actually any kind of error or failing, the plugin works just fine for multi-site installs.

**Comment by daggerhart** [comment]
Thanks @daveboulden for the update and verification that this works with multisite. 

I develope against a multisite install, so I'm pretty comforable closing this issue with an answer of "Yes, works with multisite".
